repos:
  - repo: https://github.com/dotnet/format
    rev: v5.1.225507
    hooks:
    - id: dotnet-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: check-json
    - id: check-added-large-files
